package androidx.constraintlayout.widget;

public final class R {
    private R() {
    }

    public static final class attr {
        public static final int barrierAllowsGoneWidgets = 2130903106;
        public static final int barrierDirection = 2130903107;
        public static final int chainUseRtl = 2130903152;
        public static final int constraintSet = 2130903222;
        public static final int constraint_referenced_ids = 2130903223;
        public static final int content = 2130903224;
        public static final int emptyVisibility = 2130903286;
        public static final int layout_constrainedHeight = 2130903392;
        public static final int layout_constrainedWidth = 2130903393;
        public static final int layout_constraintBaseline_creator = 2130903394;
        public static final int layout_constraintBaseline_toBaselineOf = 2130903395;
        public static final int layout_constraintBottom_creator = 2130903396;
        public static final int layout_constraintBottom_toBottomOf = 2130903397;
        public static final int layout_constraintBottom_toTopOf = 2130903398;
        public static final int layout_constraintCircle = 2130903399;
        public static final int layout_constraintCircleAngle = 2130903400;
        public static final int layout_constraintCircleRadius = 2130903401;
        public static final int layout_constraintDimensionRatio = 2130903402;
        public static final int layout_constraintEnd_toEndOf = 2130903403;
        public static final int layout_constraintEnd_toStartOf = 2130903404;
        public static final int layout_constraintGuide_begin = 2130903405;
        public static final int layout_constraintGuide_end = 2130903406;
        public static final int layout_constraintGuide_percent = 2130903407;
        public static final int layout_constraintHeight_default = 2130903408;
        public static final int layout_constraintHeight_max = 2130903409;
        public static final int layout_constraintHeight_min = 2130903410;
        public static final int layout_constraintHeight_percent = 2130903411;
        public static final int layout_constraintHorizontal_bias = 2130903412;
        public static final int layout_constraintHorizontal_chainStyle = 2130903413;
        public static final int layout_constraintHorizontal_weight = 2130903414;
        public static final int layout_constraintLeft_creator = 2130903415;
        public static final int layout_constraintLeft_toLeftOf = 2130903416;
        public static final int layout_constraintLeft_toRightOf = 2130903417;
        public static final int layout_constraintRight_creator = 2130903418;
        public static final int layout_constraintRight_toLeftOf = 2130903419;
        public static final int layout_constraintRight_toRightOf = 2130903420;
        public static final int layout_constraintStart_toEndOf = 2130903421;
        public static final int layout_constraintStart_toStartOf = 2130903422;
        public static final int layout_constraintTop_creator = 2130903423;
        public static final int layout_constraintTop_toBottomOf = 2130903424;
        public static final int layout_constraintTop_toTopOf = 2130903425;
        public static final int layout_constraintVertical_bias = 2130903426;
        public static final int layout_constraintVertical_chainStyle = 2130903427;
        public static final int layout_constraintVertical_weight = 2130903428;
        public static final int layout_constraintWidth_default = 2130903429;
        public static final int layout_constraintWidth_max = 2130903430;
        public static final int layout_constraintWidth_min = 2130903431;
        public static final int layout_constraintWidth_percent = 2130903432;
        public static final int layout_editor_absoluteX = 2130903434;
        public static final int layout_editor_absoluteY = 2130903435;
        public static final int layout_goneMarginBottom = 2130903436;
        public static final int layout_goneMarginEnd = 2130903437;
        public static final int layout_goneMarginLeft = 2130903438;
        public static final int layout_goneMarginRight = 2130903439;
        public static final int layout_goneMarginStart = 2130903440;
        public static final int layout_goneMarginTop = 2130903441;
        public static final int layout_optimizationLevel = 2130903445;

        private attr() {
        }
    }

    public static final class id {
        public static final int bottom = 2131230815;
        public static final int end = 2131230911;
        public static final int gone = 2131230945;
        public static final int invisible = 2131231000;
        public static final int left = 2131231085;
        public static final int packed = 2131231164;
        public static final int parent = 2131231167;
        public static final int percent = 2131231170;
        public static final int right = 2131231206;
        public static final int spread = 2131231278;
        public static final int spread_inside = 2131231279;
        public static final int start = 2131231284;
        public static final int top = 2131231433;
        public static final int wrap = 2131231478;

        private id() {
        }
    }

    public static final class styleable {
        public static final int[] ConstraintLayout_Layout = {16842948, 16843039, 16843040, 16843071, 16843072, com.samsung.accessory.neobeanmgr.R.attr.barrierAllowsGoneWidgets, com.samsung.accessory.neobeanmgr.R.attr.barrierDirection, com.samsung.accessory.neobeanmgr.R.attr.chainUseRtl, com.samsung.accessory.neobeanmgr.R.attr.constraintSet, com.samsung.accessory.neobeanmgr.R.attr.constraint_referenced_ids, com.samsung.accessory.neobeanmgr.R.attr.layout_constrainedHeight, com.samsung.accessory.neobeanmgr.R.attr.layout_constrainedWidth, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBaseline_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBaseline_toBaselineOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBottom_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBottom_toBottomOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBottom_toTopOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintCircle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintCircleAngle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintCircleRadius, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintDimensionRatio, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintEnd_toEndOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintEnd_toStartOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintGuide_begin, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintGuide_end, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintGuide_percent, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_default, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_max, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_min, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_percent, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHorizontal_bias, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHorizontal_chainStyle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHorizontal_weight, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintLeft_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintLeft_toLeftOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintLeft_toRightOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintRight_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintRight_toLeftOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintRight_toRightOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintStart_toEndOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintStart_toStartOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintTop_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintTop_toBottomOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintTop_toTopOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintVertical_bias, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintVertical_chainStyle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintVertical_weight, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_default, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_max, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_min, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_percent, com.samsung.accessory.neobeanmgr.R.attr.layout_editor_absoluteX, com.samsung.accessory.neobeanmgr.R.attr.layout_editor_absoluteY, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginBottom, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginEnd, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginLeft, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginRight, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginStart, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginTop, com.samsung.accessory.neobeanmgr.R.attr.layout_optimizationLevel};
        public static final int ConstraintLayout_Layout_android_maxHeight = 2;
        public static final int ConstraintLayout_Layout_android_maxWidth = 1;
        public static final int ConstraintLayout_Layout_android_minHeight = 4;
        public static final int ConstraintLayout_Layout_android_minWidth = 3;
        public static final int ConstraintLayout_Layout_android_orientation = 0;
        public static final int ConstraintLayout_Layout_barrierAllowsGoneWidgets = 5;
        public static final int ConstraintLayout_Layout_barrierDirection = 6;
        public static final int ConstraintLayout_Layout_chainUseRtl = 7;
        public static final int ConstraintLayout_Layout_constraintSet = 8;
        public static final int ConstraintLayout_Layout_constraint_referenced_ids = 9;
        public static final int ConstraintLayout_Layout_layout_constrainedHeight = 10;
        public static final int ConstraintLayout_Layout_layout_constrainedWidth = 11;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_creator = 12;
        public static final int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 13;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_creator = 14;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 15;
        public static final int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 16;
        public static final int ConstraintLayout_Layout_layout_constraintCircle = 17;
        public static final int ConstraintLayout_Layout_layout_constraintCircleAngle = 18;
        public static final int ConstraintLayout_Layout_layout_constraintCircleRadius = 19;
        public static final int ConstraintLayout_Layout_layout_constraintDimensionRatio = 20;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 21;
        public static final int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 22;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_begin = 23;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_end = 24;
        public static final int ConstraintLayout_Layout_layout_constraintGuide_percent = 25;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_default = 26;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_max = 27;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_min = 28;
        public static final int ConstraintLayout_Layout_layout_constraintHeight_percent = 29;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 30;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_chainStyle = 31;
        public static final int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 32;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_creator = 33;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 34;
        public static final int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 35;
        public static final int ConstraintLayout_Layout_layout_constraintRight_creator = 36;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 37;
        public static final int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 38;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 39;
        public static final int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 40;
        public static final int ConstraintLayout_Layout_layout_constraintTop_creator = 41;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 42;
        public static final int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 43;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_bias = 44;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_chainStyle = 45;
        public static final int ConstraintLayout_Layout_layout_constraintVertical_weight = 46;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_default = 47;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_max = 48;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_min = 49;
        public static final int ConstraintLayout_Layout_layout_constraintWidth_percent = 50;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteX = 51;
        public static final int ConstraintLayout_Layout_layout_editor_absoluteY = 52;
        public static final int ConstraintLayout_Layout_layout_goneMarginBottom = 53;
        public static final int ConstraintLayout_Layout_layout_goneMarginEnd = 54;
        public static final int ConstraintLayout_Layout_layout_goneMarginLeft = 55;
        public static final int ConstraintLayout_Layout_layout_goneMarginRight = 56;
        public static final int ConstraintLayout_Layout_layout_goneMarginStart = 57;
        public static final int ConstraintLayout_Layout_layout_goneMarginTop = 58;
        public static final int ConstraintLayout_Layout_layout_optimizationLevel = 59;
        public static final int[] ConstraintLayout_placeholder = {com.samsung.accessory.neobeanmgr.R.attr.content, com.samsung.accessory.neobeanmgr.R.attr.emptyVisibility};
        public static final int ConstraintLayout_placeholder_content = 0;
        public static final int ConstraintLayout_placeholder_emptyVisibility = 1;
        public static final int[] ConstraintSet = {16842948, 16842960, 16842972, 16842996, 16842997, 16842999, 16843000, 16843001, 16843002, 16843039, 16843040, 16843071, 16843072, 16843551, 16843552, 16843553, 16843554, 16843555, 16843556, 16843557, 16843558, 16843559, 16843560, 16843701, 16843702, 16843770, 16843840, com.samsung.accessory.neobeanmgr.R.attr.barrierAllowsGoneWidgets, com.samsung.accessory.neobeanmgr.R.attr.barrierDirection, com.samsung.accessory.neobeanmgr.R.attr.chainUseRtl, com.samsung.accessory.neobeanmgr.R.attr.constraint_referenced_ids, com.samsung.accessory.neobeanmgr.R.attr.layout_constrainedHeight, com.samsung.accessory.neobeanmgr.R.attr.layout_constrainedWidth, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBaseline_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBaseline_toBaselineOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBottom_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBottom_toBottomOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintBottom_toTopOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintCircle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintCircleAngle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintCircleRadius, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintDimensionRatio, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintEnd_toEndOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintEnd_toStartOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintGuide_begin, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintGuide_end, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintGuide_percent, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_default, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_max, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_min, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHeight_percent, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHorizontal_bias, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHorizontal_chainStyle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintHorizontal_weight, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintLeft_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintLeft_toLeftOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintLeft_toRightOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintRight_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintRight_toLeftOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintRight_toRightOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintStart_toEndOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintStart_toStartOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintTop_creator, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintTop_toBottomOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintTop_toTopOf, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintVertical_bias, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintVertical_chainStyle, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintVertical_weight, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_default, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_max, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_min, com.samsung.accessory.neobeanmgr.R.attr.layout_constraintWidth_percent, com.samsung.accessory.neobeanmgr.R.attr.layout_editor_absoluteX, com.samsung.accessory.neobeanmgr.R.attr.layout_editor_absoluteY, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginBottom, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginEnd, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginLeft, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginRight, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginStart, com.samsung.accessory.neobeanmgr.R.attr.layout_goneMarginTop};
        public static final int ConstraintSet_android_alpha = 13;
        public static final int ConstraintSet_android_elevation = 26;
        public static final int ConstraintSet_android_id = 1;
        public static final int ConstraintSet_android_layout_height = 4;
        public static final int ConstraintSet_android_layout_marginBottom = 8;
        public static final int ConstraintSet_android_layout_marginEnd = 24;
        public static final int ConstraintSet_android_layout_marginLeft = 5;
        public static final int ConstraintSet_android_layout_marginRight = 7;
        public static final int ConstraintSet_android_layout_marginStart = 23;
        public static final int ConstraintSet_android_layout_marginTop = 6;
        public static final int ConstraintSet_android_layout_width = 3;
        public static final int ConstraintSet_android_maxHeight = 10;
        public static final int ConstraintSet_android_maxWidth = 9;
        public static final int ConstraintSet_android_minHeight = 12;
        public static final int ConstraintSet_android_minWidth = 11;
        public static final int ConstraintSet_android_orientation = 0;
        public static final int ConstraintSet_android_rotation = 20;
        public static final int ConstraintSet_android_rotationX = 21;
        public static final int ConstraintSet_android_rotationY = 22;
        public static final int ConstraintSet_android_scaleX = 18;
        public static final int ConstraintSet_android_scaleY = 19;
        public static final int ConstraintSet_android_transformPivotX = 14;
        public static final int ConstraintSet_android_transformPivotY = 15;
        public static final int ConstraintSet_android_translationX = 16;
        public static final int ConstraintSet_android_translationY = 17;
        public static final int ConstraintSet_android_translationZ = 25;
        public static final int ConstraintSet_android_visibility = 2;
        public static final int ConstraintSet_barrierAllowsGoneWidgets = 27;
        public static final int ConstraintSet_barrierDirection = 28;
        public static final int ConstraintSet_chainUseRtl = 29;
        public static final int ConstraintSet_constraint_referenced_ids = 30;
        public static final int ConstraintSet_layout_constrainedHeight = 31;
        public static final int ConstraintSet_layout_constrainedWidth = 32;
        public static final int ConstraintSet_layout_constraintBaseline_creator = 33;
        public static final int ConstraintSet_layout_constraintBaseline_toBaselineOf = 34;
        public static final int ConstraintSet_layout_constraintBottom_creator = 35;
        public static final int ConstraintSet_layout_constraintBottom_toBottomOf = 36;
        public static final int ConstraintSet_layout_constraintBottom_toTopOf = 37;
        public static final int ConstraintSet_layout_constraintCircle = 38;
        public static final int ConstraintSet_layout_constraintCircleAngle = 39;
        public static final int ConstraintSet_layout_constraintCircleRadius = 40;
        public static final int ConstraintSet_layout_constraintDimensionRatio = 41;
        public static final int ConstraintSet_layout_constraintEnd_toEndOf = 42;
        public static final int ConstraintSet_layout_constraintEnd_toStartOf = 43;
        public static final int ConstraintSet_layout_constraintGuide_begin = 44;
        public static final int ConstraintSet_layout_constraintGuide_end = 45;
        public static final int ConstraintSet_layout_constraintGuide_percent = 46;
        public static final int ConstraintSet_layout_constraintHeight_default = 47;
        public static final int ConstraintSet_layout_constraintHeight_max = 48;
        public static final int ConstraintSet_layout_constraintHeight_min = 49;
        public static final int ConstraintSet_layout_constraintHeight_percent = 50;
        public static final int ConstraintSet_layout_constraintHorizontal_bias = 51;
        public static final int ConstraintSet_layout_constraintHorizontal_chainStyle = 52;
        public static final int ConstraintSet_layout_constraintHorizontal_weight = 53;
        public static final int ConstraintSet_layout_constraintLeft_creator = 54;
        public static final int ConstraintSet_layout_constraintLeft_toLeftOf = 55;
        public static final int ConstraintSet_layout_constraintLeft_toRightOf = 56;
        public static final int ConstraintSet_layout_constraintRight_creator = 57;
        public static final int ConstraintSet_layout_constraintRight_toLeftOf = 58;
        public static final int ConstraintSet_layout_constraintRight_toRightOf = 59;
        public static final int ConstraintSet_layout_constraintStart_toEndOf = 60;
        public static final int ConstraintSet_layout_constraintStart_toStartOf = 61;
        public static final int ConstraintSet_layout_constraintTop_creator = 62;
        public static final int ConstraintSet_layout_constraintTop_toBottomOf = 63;
        public static final int ConstraintSet_layout_constraintTop_toTopOf = 64;
        public static final int ConstraintSet_layout_constraintVertical_bias = 65;
        public static final int ConstraintSet_layout_constraintVertical_chainStyle = 66;
        public static final int ConstraintSet_layout_constraintVertical_weight = 67;
        public static final int ConstraintSet_layout_constraintWidth_default = 68;
        public static final int ConstraintSet_layout_constraintWidth_max = 69;
        public static final int ConstraintSet_layout_constraintWidth_min = 70;
        public static final int ConstraintSet_layout_constraintWidth_percent = 71;
        public static final int ConstraintSet_layout_editor_absoluteX = 72;
        public static final int ConstraintSet_layout_editor_absoluteY = 73;
        public static final int ConstraintSet_layout_goneMarginBottom = 74;
        public static final int ConstraintSet_layout_goneMarginEnd = 75;
        public static final int ConstraintSet_layout_goneMarginLeft = 76;
        public static final int ConstraintSet_layout_goneMarginRight = 77;
        public static final int ConstraintSet_layout_goneMarginStart = 78;
        public static final int ConstraintSet_layout_goneMarginTop = 79;
        public static final int[] LinearConstraintLayout = {16842948};
        public static final int LinearConstraintLayout_android_orientation = 0;

        private styleable() {
        }
    }
}
